import {Text} from "react-native";

const content = {
    'Expenses': 'Расходы',
    'Current expenses': 'Текущие расходы',
    'Account': 'Счёт',
    'Balance': 'Баланс',
    'Spent': 'Потрачено',
    'Plan': 'План',
    'Plans': 'Планы',
    'Period': 'Период',
    'Current plans': 'Текущие планы',
    'Add Income': 'Добавить доход',
    'Rent / Mortgage': 'Аренда / Ипотека',
    'Utilities': 'Комуналка',
    'Credits / Debts': 'Кредиты / Долги',
    'Taxes': 'Налоги',
    'Groceries': 'Продукты',
    'Transport': 'Транспорт',
    'Services': 'Услуги',
    'Beauty & Health': 'Красота и Здоровье',
    'Having Fun': 'Развлечение',
    'Eating Out': 'Кафе и Рестораны',
    'Shopping / Clothes': 'Шоппинг / Одежда',
    'Hobbies': 'Хобби',
    'Gifts': 'Подарки',
    'Education': 'Обучение',
    'Others': 'Прочие',
    'plan / fact': 'план / факт',
    'You can schedule a new expense': 'Вы можете запланировать расход',
    'OR': 'ИЛИ',
    'You can write down a new expense': 'Вы можете записать расход',
    'Plan expense': 'Запланировать расход',
    'Make expense': 'Записать расход',
    'Dark mode': 'Тёмная тема',
    'Language': 'Язык',
    'english': 'английский',
    'russian': 'русский',
    'Home': 'Главная',
    'Goals': 'Цели',
    'Settings': 'Настройки',
    'Expense Editor': 'Редактор Расходов',
    'Removing expense': 'Удаление расхода',
    'Do you really want to remove the expense?': 'Вы действительно хотите удалить расход?',
    'Category:': 'Категория:',
    'Cancel': 'Отмена',
    'Save': 'Сохранить',
    'remove': 'удалить',
    'Expense:': 'Расход:',
    'Sum:': 'Сумма:',
    'Enter expense name': 'Введите название расхода',
    'Enter money spent': 'Введите затраченную сумму',
    'Error!': 'Ошибка!',
    'Minimum three symbols': 'В название должно быть не менее трёх символов',
    'Income Editor': 'Редактор Доходов',
    'Removing income': 'Удаление дохода',
    'Do you really want to remove the income?': 'Вы действительно хотите удалить доход?',
    'Income:': 'Доход:',
    'income': 'доход',
    'Enter income name': 'Введите название дохода',
    'Enter money earned': 'Введите полученную сумму',
    'Planning Expense': 'Планирование расходов',
    'SETTINGS': 'НАСТРОЙКИ',
    'Removing plan': 'Удаление плана',
    'Do you really want to remove the plan?': 'Вы действительно хотите удалить план?',
    'You need to fill sum': 'Вам необходимо ввести суму',
    'Do you want to execute the plan?': 'Выполнить план?',
    'Plan: ': 'План: ',
    'Price: ': 'Цена: ',
    'Fact: ': 'Факт: ',
    'done': 'выполнить',
    'Choose date for paying': 'Выберите планируемую дату расхода',
    'Expense name:': 'Название расхода',
    'Time limit': 'Временной предел',
    'Target date: ': 'Дата плана',
    'Done': 'Выполнить',
    'january': 'январь',
    'february': 'февраль',
    'march': 'март',
    'april': 'апрель',
    'may': 'май',
    'june': 'июнь',
    'july': 'июль',
    'august': 'август',
    'september': 'сентябрь',
    'october': 'октябрь',
    'november': 'ноябрь',
    'december': 'декабрь',
    'January': 'Январь',
    'February': 'Февраль',
    'March': 'Март',
    'April': 'Апрель',
    'May': 'Май',
    'June': 'Июнь',
    'July': 'Июль',
    'August': 'Август',
    'September': 'Сентябрь',
    'October': 'Октябрь',
    'November': 'Ноябрь',
    'December': 'Декабрь',
    'submit': 'принять',
    'change': 'изменить',
    'Enter the money you plan to spend': 'Введите планируемую сумму',
    "Plan can't be less than": 'Сумма плана не может быть меньше',
    'change plan': 'изменить план',
    'money left': 'осталось денег',
    'total money': 'всего денег',
    'total income': 'всего заработано',
    'total spent': 'всего потрачено',
    'Loading': 'Загрузка',
    'Reports': 'Отчеты',
    'Earned in month': 'Заработано за месяц',
    'Saved in month': 'Сэкономлено за месяц',
    'Spent in month': 'Потрачено за месяц',
    'Left from previous month': 'Остаток с прошлого месяца',
    'All time': 'За всё время',
    'private finance detective': 'часный финансовый детектив',
    'in': 'через',
    'days': 'дней',
    'others': 'прочие',
    'Savings': 'Накопления',
    'You are trying to take more then you have!': 'Вы пытаетесь взять больше чем у вас есть!',
    'Current account': 'Текущий счет',
    'Try to save some money every month. Take your savings on different account or save it in cash. The main thing you must think of - is not thinking of them! Give it time and your savings will grown.':'Попытайтесь откладывать деньги каждый месяц. Переводите свои сбережения на другой счет или храните наличными. Главное, о чем нужно думать - не думать о них! Дайте время, и ваши сбережения вырастут.',
    'Withdraw money': 'Снять деньги',
    'Transfer to savings': 'Перевести в сбережения',
    'Enter the sum': 'Введите сумму',
    'You are trying to spend more then you have!': 'Вы пытаетесь взять больше чем у вас есть!',
    'Check your balance': 'Проверьте свой баланс',
    'There is no data yet': 'Нет данных',
    'Coming up soon!': 'Скоро появится!',
    'LOADING...': 'ЗАГРУЗКА...'
}


export const lang = (text, language) => {
    if (language === 'english') {
        return text
    }
    return content[text]
}
